services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cloud-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1234
    ports:
      - "1433:1433"

  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: cloud-backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: dotnet watch run --urls http://0.0.0.0:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    image: node:24-slim
    container_name: cloud-frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    depends_on:
      - backend
